### ISSUE TITLE
Upload to SciDraw maybe ?

### ISSUE THREAD

**Issue by FedeClaudi** [arielfeldman/parrotpack#1]
Hi,

I really like your drawings and I think it's great that you've decided to make them publicly available. 

I've recently launched a website (www.scidraw.io) that aims to be a free repository of high quality drawings for scientific talks and publications. If you would like I could add your drawings to the website under your name :)

Thank you, 
Federico

**Comment by arielfeldman** [comment]
Hi Federico,

I have no problem with you adding my drawings so long as you attribute proper credit! I should have some more updated images soon as well :) sorry for the delayed response, I was a bit preoccupied with SfN recently. Always glad to see others making these sorts of things more accessible to the scientific community!

Cheers,
Ariel

**Comment by FedeClaudi** [comment]
Hi, 

That is great, I'm delighted to hear that you would be happy to share your work on SciDraw too!
I can add your drawings with you as author and your website/twitter handle (which I don't know unfortunately), but you can also upload them directly if you want to make sure you're happy with the details (https://scidraw.io/upload/)!

Either way, thank you!

**Comment by arielfeldman** [comment]
I'll try and upload them tonight or tomorrow then! I also noticed y'all include rat drawings -- in case you're interested, a former lab member of mine created [ratpack](https://github.com/eackermann/ratpack), which you may be interested in conversing with him about using as well.

**Comment by FedeClaudi** [comment]
That's great, thanks. If you have any problem just let me know and I will upload them for you. 

And thanks! Ratpack looks awesome, I was not aware of it, I will get in touch with them too. We are trying to group as much material on as many species as possible, so thank you very much for your tip (and for sharing your work)
